using System;
using Amazon.CDK;
using Amazon.CDK.AWS.EC2;
using Amazon.CDK.AWS.ECS;
using Amazon.CDK.AWS.ECS.Patterns;

public class FargateSampleStack : Stack
{
    internal FargateSampleStack(Construct scope, string id, IStackProps props = null) 
		: base(scope, id, props)
    {
        var serviceProps = new ApplicationLoadBalancedFargateServiceProps
        {
            MemoryLimitMiB = 512,
            Cpu = 256,
            AssignPublicIp = true,
            TaskImageOptions = new ApplicationLoadBalancedTaskImageOptions
            {
				// Sample app is a .NET 6 Blazor Server app generated by
				// Visual Studio, referenced by path relative to cdk.json
                Image = ContainerImage.FromAsset("./sample-app")
            },
			// note: not all accounts have a default vpc
            Vpc = Vpc.FromLookup(this, id = "MyDefaultVpc", new VpcLookupOptions
            {
                IsDefault = true
            })
        };

        var service
            = new ApplicationLoadBalancedFargateService(this, "BlazorServerSample", serviceProps);
    }
}
