version: 0.0
os: linux
files:
  - source: /index.html
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: ./before_install.sh
      timeout: 300
  AfterInstall:
    - location: ./restart_server.sh
      timeout: 300